Tasks from the 'arrays' folder
glebkodev/ru-study-ruby pull request #1
Opened 2022-09-28 19:24 UTC by glebkodev

2022-09-29 19:27 UTC, NickelGit requested changes

2022-09-29 19:27 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        new_array
перепиши пжлст с использованием функции .map которая по итогу своей работы сразу вернет новый массив 
https://www.rubyguides.com/2018/10/ruby-map-method/

2022-09-29 19:27 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        -1
вложенность ухудшает читаемость, лучше представить это в виде нескольких guard clause которые будут проверять есть ли что то в массиве, нашли ли мы уже искомый элемент, и находится ли вообще элемент который мы ищем в границах нашего массива
https://anthonygharvey.com/guard-clauses-vs-nested-conditionals

И вместо цикла лучше использовать рекурсивный вызов функции с аргументами по умолчанию для первого вызова
https://medium.com/@sologoubalex/parameters-with-default-values-in-ruby-74cd0e830681

2022-09-29 22:46 UTC, glebkodev commented
@NickelGit спасибо за комментарии, исправил.

2022-09-30 06:00 UTC, NickelGit requested changes

2022-09-30 06:00 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        return -1 if left > right
Бинарный поиск возможен только в отсортированном массиве, поэтому мы точно знаем что слева всегда будет наименьшее значение, а справа наибольшее.
добавь пжлст проверку находится ли вообще элемент который мы ищем в границах нашего поиска.

2022-09-30 06:00 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        mid = (left + right) / 2
добавь после этой строки пжлст guard clause который будет проверять равен ли средний элемент тому что мы искали.

2022-09-30 06:00 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        return search(array, query, left, mid - 1) if query < array[mid]
если мы добавим сверху guard clause с проверкой что мы нашли то что искали, это позволит нам удалить тут `return`. Давай перепишем смещение границ поиска в виде тернарной операции.

2022-09-30 06:00 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        mid
mid будет возвращаться из guard clause в случае если мы найдем нужный элемент. Этот возврат можно удалить.

2022-09-30 08:23 UTC, glebkodev commented on test/exercise/arrays/solution.rb
> +        return -1 if left > right
Этот момент не совсем понял. У меня left и right - это границы (индексы) массива при поиске, если выполняется условие left > right , то значит мы вышли за границы массива и элемент не найден. 

Добавил также проверку методом .empty? для массива, чтобы сразу возвращалось -1.

2022-09-30 08:28 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        return -1 if left > right
`empty?` уже избыточен, т.к. для пустого массива по умолчанию границы станут left=0, right=-1. И сработает твоя изначальная проверка.
Я говорю про эти случаи
```
ищем -100, в массиве [-10, 0, 1, 10]
ищем 100, в массиве [-10, 0, 1, 10]
ищем 35, в массиве [1, 2, 3, 10, 20, 30, 40, 50] 
```

т.е. нам надо еще проверять находится ли вообще элемент который мы ищем в наших текущих границах поиска

2022-09-30 09:19 UTC, glebkodev commented on test/exercise/arrays/solution.rb
> +        return -1 if left > right
Спасибо! Добавил проверку.

2022-09-30 09:50 UTC, NickelGit approved these changes

2022-09-30 14:16 UTC, merged